# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='房间名')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, '上午八点'), (2, '上午九点'), (3, '上午十点'), (4, '上午十一点'), (5, '上午十二点'), (6, '下午一点'), (7, '下午两点'), (8, '下午三点'), (9, '下午四点'), (10, '下午五点'), (11, '下午六点'), (12, '下午七点')], verbose_name='选择时间段')),
                ('create_time', models.DateTimeField(verbose_name='预约时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='Reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='预约人'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomdetail',
            field=models.ManyToManyField(to='app01.RoomDetail'),
        ),
    ]
