# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomdetail',
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='Room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Room', verbose_name='选择会议室'),
            preserve_default=False,
        ),
    ]
