# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171208_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='create_time',
            field=models.DateField(verbose_name='预约时间'),
        ),
    ]
