# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171208_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetail',
            old_name='Reservation',
            new_name='reservation',
        ),
        migrations.RenameField(
            model_name='roomdetail',
            old_name='Room',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=32, verbose_name='会议室名'),
        ),
    ]
